$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: suriyak-dep-2
endpoint_name: suriyak-ep-2
private_network_connection: true
model:
  name: suriyak-model-2
  version: 2
  local_path: ./
environment:
  name: suriyak-env-2
  version: 2
  image: suriyakeuapregistry.azurecr.io/suriyakalivardhan/simpleinferencer:v1
  inference_config:
    liveness_route:
      port: 5001
      path: /healthcheck
    readiness_route:
      port: 5001
      path: /healthcheck
    scoring_route:
      port: 5001
      path: /inference
instance_type: Standard_F2s_v2
instance_count: 1